export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAILURE = 'ORDER_PAYMENT_FAILURE';
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET';
